### ISSUE TITLE
Suggestion Train Sounds

### ISSUE THREAD

**Issue by suerion** [WheteThunger/AutomatedWorkcarts#4]
Hey, we had looking on an changing for this Addon, but we don't found a solution

could you add, Trains should not make any noises?

i had looked on the rust source code, 

TrainCar
TrainCarAudio
TrainEngine
TrainEngineAudio

Could you add soundoptions on your Plugin -> Train should not make any noises, on rail, on start, on movement,

but we don't get yet an solution -> on codefling discord i had get an hint from bmgjet -> 

            FieldInfo _trainCarAudio = typeof(TrainCar).GetField("trainCarAudio", BindingFlags.Instance | BindingFlags.NonPublic);

            _trainCarAudio.SetValue(TrainCarReference, null);

**Comment by WheteThunger** [comment]
I don't think altering the sounds is possible. These sounds are not emitted by the server (relevant because this is a server side plugin). The sounds are generated by game clients according to the state of the train cars. Even if the plugin were to alter the trainCarAudio property of a given train car on the server, the client would have no way of knowing, since the value of that property is not sent to clients (and there is no communication protocol that would allow such a message to be sent).

Below is the implementation of the Save() method for the TrainEngine and TrainCar classes. The Save() method is used for saving to disk, as well as for networking entity state to clients.

TrainEngine:

```cs
info.msg.trainEngine = Facepunch.Pool.Get<ProtoBuf.TrainEngine>();
info.msg.trainEngine.throttleSetting = (int)CurThrottleSetting;
info.msg.trainEngine.fuelStorageID = GetFuelSystem().fuelStorageInstance.uid;
info.msg.trainEngine.fuelAmount = GetFuelAmount();
info.msg.trainEngine.numConnectedCars = completeTrain.NumTrainCars;
```

TrainCar:

```cs
info.msg.baseTrain = Pool.Get<BaseTrain>();
info.msg.baseTrain.time = GetNetworkTime();
info.msg.baseTrain.frontBogieYRot = frontBogieYRot;
info.msg.baseTrain.rearBogieYRot = rearBogieYRot;
if (coupling.frontCoupling.TryGetCoupledToID(out var id))
{
    info.msg.baseTrain.frontCouplingID = id;
    info.msg.baseTrain.frontCouplingToFront = coupling.frontCoupling.CoupledTo.isFrontCoupling;
}
if (coupling.rearCoupling.TryGetCoupledToID(out id))
{
    info.msg.baseTrain.rearCouplingID = id;
    info.msg.baseTrain.rearCouplingToFront = coupling.rearCoupling.CoupledTo.isFrontCoupling;
}
```

The available RPC methods are:
- SetThrottle (TrainEngine)
- SetFuelAmount (TrainEngine)
- BaseTrainUpdate (TrainCar)
- SetTrackSelection (TrainCar)

Experimentation with the above fields and RPC calls might reveal an edge case that can be used to make the trains stop making sounds, but it would likely result in side effects such as the wheels not moving.

**Comment by suerion** [comment]
Hey, thanks, for yor answere, we had your plugin added on our side, because we had an RP server, but the trains are a little bit loud, yet we thougt, we could add some code on server to kill the sound... but if it is client sided, it would be a mess...

 and what do you think do the "CanNetworkTo"?

`bool CanNetworkTo(BaseNetworkable entity, BasePlayer target)`

**Comment by WheteThunger** [comment]
The purpose of the `CanNetworkTo` hook is to decide whether each train car is networked to a given player. It could be used to hide a train car, which would of course mute the sound, but the train car would be invisible. Also, the `CanNetworkTo` hook incurs a huge performance cost so it should never be used.

**Comment by suerion** [comment]
okey, thanks a lot :)
